# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toolkit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtoolkit.proto\x12\x12trpc.media.toolkit\x1a\x0c\x63ommon.proto\"\xbb\x01\n\x08ToolInfo\x12\x0e\n\x06ToolID\x18\x01 \x01(\t\x12\x10\n\x08ToolName\x18\x02 \x01(\t\x12\x17\n\x0fToolDescription\x18\x03 \x01(\t\x12\x13\n\x0bToolIconURI\x18\x04 \x01(\t\x12\x14\n\x0cToolEntryURI\x18\x05 \x01(\t\x12\x36\n\nToolAccess\x18\x08 \x01(\x0e\x32\".trpc.media.toolkit.ToolAccessType\x12\x11\n\tToolOrder\x18\t \x01(\x05\"\x19\n\x17\x44\x65scribeToolkitsRequest\"I\n\x18\x44\x65scribeToolkitsResponse\x12-\n\x07ToolSet\x18\x01 \x03(\x0b\x32\x1c.trpc.media.toolkit.ToolInfo\"\x17\n\x15ToolkitDefaultRequest\"\x18\n\x16ToolkitDefaultResponse*_\n\x10ToolProviderType\x12\x19\n\x15TOOL_PROVIDER_UNKNOWN\x10\x00\x12\x19\n\x15TOOL_PROVIDER_AIMEDIA\x10\x01\x12\x15\n\x11TOOL_PROVIDER_PCG\x10\x02*u\n\x10ToolCategoryType\x12\x19\n\x15TOOL_CATEGORY_UNKNOWN\x10\x00\x12\x1f\n\x1bTOOL_CATEGORY_VIDEO_QUALITY\x10\x01\x12%\n!TOOL_CATEGORY_VIDEO_UNDERSTANDING\x10\x02*]\n\x0eToolAccessType\x12\x17\n\x13TOOL_ACCESS_UNKNOWN\x10\x00\x12\x18\n\x14TOOL_ACCESS_INTERNAL\x10\x01\x12\x18\n\x14TOOL_ACCESS_EXTERNAL\x10\x02\x32x\n\x07Toolkit\x12m\n\x10\x44\x65scribeToolkits\x12+.trpc.media.toolkit.DescribeToolkitsRequest\x1a,.trpc.media.toolkit.DescribeToolkitsResponseBWZUgithub.com/Tencent-media-asset-system-sdk/media-platform-sdk-go/protobuf-spec/toolkitb\x06proto3')

_TOOLPROVIDERTYPE = DESCRIPTOR.enum_types_by_name['ToolProviderType']
ToolProviderType = enum_type_wrapper.EnumTypeWrapper(_TOOLPROVIDERTYPE)
_TOOLCATEGORYTYPE = DESCRIPTOR.enum_types_by_name['ToolCategoryType']
ToolCategoryType = enum_type_wrapper.EnumTypeWrapper(_TOOLCATEGORYTYPE)
_TOOLACCESSTYPE = DESCRIPTOR.enum_types_by_name['ToolAccessType']
ToolAccessType = enum_type_wrapper.EnumTypeWrapper(_TOOLACCESSTYPE)
TOOL_PROVIDER_UNKNOWN = 0
TOOL_PROVIDER_AIMEDIA = 1
TOOL_PROVIDER_PCG = 2
TOOL_CATEGORY_UNKNOWN = 0
TOOL_CATEGORY_VIDEO_QUALITY = 1
TOOL_CATEGORY_VIDEO_UNDERSTANDING = 2
TOOL_ACCESS_UNKNOWN = 0
TOOL_ACCESS_INTERNAL = 1
TOOL_ACCESS_EXTERNAL = 2


_TOOLINFO = DESCRIPTOR.message_types_by_name['ToolInfo']
_DESCRIBETOOLKITSREQUEST = DESCRIPTOR.message_types_by_name['DescribeToolkitsRequest']
_DESCRIBETOOLKITSRESPONSE = DESCRIPTOR.message_types_by_name['DescribeToolkitsResponse']
_TOOLKITDEFAULTREQUEST = DESCRIPTOR.message_types_by_name['ToolkitDefaultRequest']
_TOOLKITDEFAULTRESPONSE = DESCRIPTOR.message_types_by_name['ToolkitDefaultResponse']
ToolInfo = _reflection.GeneratedProtocolMessageType('ToolInfo', (_message.Message,), {
  'DESCRIPTOR' : _TOOLINFO,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.ToolInfo)
  })
_sym_db.RegisterMessage(ToolInfo)

DescribeToolkitsRequest = _reflection.GeneratedProtocolMessageType('DescribeToolkitsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBETOOLKITSREQUEST,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.DescribeToolkitsRequest)
  })
_sym_db.RegisterMessage(DescribeToolkitsRequest)

DescribeToolkitsResponse = _reflection.GeneratedProtocolMessageType('DescribeToolkitsResponse', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBETOOLKITSRESPONSE,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.DescribeToolkitsResponse)
  })
_sym_db.RegisterMessage(DescribeToolkitsResponse)

ToolkitDefaultRequest = _reflection.GeneratedProtocolMessageType('ToolkitDefaultRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOOLKITDEFAULTREQUEST,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.ToolkitDefaultRequest)
  })
_sym_db.RegisterMessage(ToolkitDefaultRequest)

ToolkitDefaultResponse = _reflection.GeneratedProtocolMessageType('ToolkitDefaultResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOOLKITDEFAULTRESPONSE,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.ToolkitDefaultResponse)
  })
_sym_db.RegisterMessage(ToolkitDefaultResponse)

_TOOLKIT = DESCRIPTOR.services_by_name['Toolkit']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZUgithub.com/Tencent-media-asset-system-sdk/media-platform-sdk-go/protobuf-spec/toolkit'
  _TOOLPROVIDERTYPE._serialized_start=394
  _TOOLPROVIDERTYPE._serialized_end=489
  _TOOLCATEGORYTYPE._serialized_start=491
  _TOOLCATEGORYTYPE._serialized_end=608
  _TOOLACCESSTYPE._serialized_start=610
  _TOOLACCESSTYPE._serialized_end=703
  _TOOLINFO._serialized_start=52
  _TOOLINFO._serialized_end=239
  _DESCRIBETOOLKITSREQUEST._serialized_start=241
  _DESCRIBETOOLKITSREQUEST._serialized_end=266
  _DESCRIBETOOLKITSRESPONSE._serialized_start=268
  _DESCRIBETOOLKITSRESPONSE._serialized_end=341
  _TOOLKITDEFAULTREQUEST._serialized_start=343
  _TOOLKITDEFAULTREQUEST._serialized_end=366
  _TOOLKITDEFAULTRESPONSE._serialized_start=368
  _TOOLKITDEFAULTRESPONSE._serialized_end=392
  _TOOLKIT._serialized_start=705
  _TOOLKIT._serialized_end=825
# @@protoc_insertion_point(module_scope)
