# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_cut.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvideo_cut.proto\x12\x13trpc.media.videocut\"b\n\x10VideoCutTaskData\x12\x14\n\x0cVideocutSize\x18\x04 \x01(\x05\x12\x38\n\rVideocutItems\x18\x05 \x03(\x0b\x32!.trpc.media.videocut.VideoCutItem\"n\n\x0cVideoCutItem\x12\x14\n\x0cVideocutType\x18\x01 \x01(\t\x12\x11\n\tHeadIndex\x18\x02 \x01(\x05\x12\x11\n\tTailIndex\x18\x03 \x01(\x05\x12\x11\n\tStartTime\x18\x04 \x01(\x02\x12\x0f\n\x07\x45ndTime\x18\x05 \x01(\x02\x42XZVgithub.com/Tencent-media-asset-system-sdk/media-platform-sdk-go/protobuf-spec/videocutb\x06proto3')



_VIDEOCUTTASKDATA = DESCRIPTOR.message_types_by_name['VideoCutTaskData']
_VIDEOCUTITEM = DESCRIPTOR.message_types_by_name['VideoCutItem']
VideoCutTaskData = _reflection.GeneratedProtocolMessageType('VideoCutTaskData', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOCUTTASKDATA,
  '__module__' : 'video_cut_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.videocut.VideoCutTaskData)
  })
_sym_db.RegisterMessage(VideoCutTaskData)

VideoCutItem = _reflection.GeneratedProtocolMessageType('VideoCutItem', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOCUTITEM,
  '__module__' : 'video_cut_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.videocut.VideoCutItem)
  })
_sym_db.RegisterMessage(VideoCutItem)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZVgithub.com/Tencent-media-asset-system-sdk/media-platform-sdk-go/protobuf-spec/videocut'
  _VIDEOCUTTASKDATA._serialized_start=40
  _VIDEOCUTTASKDATA._serialized_end=138
  _VIDEOCUTITEM._serialized_start=140
  _VIDEOCUTITEM._serialized_end=250
# @@protoc_insertion_point(module_scope)
