# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc_mock as grpc

from . import workflow_template_pb2 as workflow__template__pb2


class WorkflowTemplateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWorkflowTemplates = channel.unary_unary(
                '/trpc.media.workflowtemplate.WorkflowTemplate/CreateWorkflowTemplates',
                request_serializer=workflow__template__pb2.CreateWorkflowTemplatesRequest.SerializeToString,
                response_deserializer=workflow__template__pb2.CreateWorkflowTemplatesResponse.FromString,
                )
        self.DescribeWorkflowTemplates = channel.unary_unary(
                '/trpc.media.workflowtemplate.WorkflowTemplate/DescribeWorkflowTemplates',
                request_serializer=workflow__template__pb2.DescribeWorkflowTemplatesRequest.SerializeToString,
                response_deserializer=workflow__template__pb2.DescribeWorkflowTemplatesResponse.FromString,
                )
        self.DescribeWorkflowTemplateDetails = channel.unary_unary(
                '/trpc.media.workflowtemplate.WorkflowTemplate/DescribeWorkflowTemplateDetails',
                request_serializer=workflow__template__pb2.DescribeWorkflowTemplateDetailsRequest.SerializeToString,
                response_deserializer=workflow__template__pb2.DescribeWorkflowTemplateDetailsResponse.FromString,
                )
        self.DeleteWorkflowTemplates = channel.unary_unary(
                '/trpc.media.workflowtemplate.WorkflowTemplate/DeleteWorkflowTemplates',
                request_serializer=workflow__template__pb2.DeleteWorkflowTemplatesRequest.SerializeToString,
                response_deserializer=workflow__template__pb2.DeleteWorkflowTemplatesResponse.FromString,
                )
        self.ModifyWorkflowTemplate = channel.unary_unary(
                '/trpc.media.workflowtemplate.WorkflowTemplate/ModifyWorkflowTemplate',
                request_serializer=workflow__template__pb2.ModifyWorkflowTemplateRequest.SerializeToString,
                response_deserializer=workflow__template__pb2.ModifyWorkflowTemplateResponse.FromString,
                )
        self.DescribeAvailableWorkflowTemplateComponents = channel.unary_unary(
                '/trpc.media.workflowtemplate.WorkflowTemplate/DescribeAvailableWorkflowTemplateComponents',
                request_serializer=workflow__template__pb2.DescribeAvailableWorkflowTemplateComponentsRequest.SerializeToString,
                response_deserializer=workflow__template__pb2.DescribeAvailableWorkflowTemplateComponentsResponse.FromString,
                )


class WorkflowTemplateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWorkflowTemplates(self, request, context):
        """工作流模板管理
        @alias=/CreateWorkflowTemplates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeWorkflowTemplates(self, request, context):
        """@alias=/DescribeWorkflowTemplates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeWorkflowTemplateDetails(self, request, context):
        """@alias=/DescribeWorkflowTemplateDetails
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWorkflowTemplates(self, request, context):
        """@alias=/DeleteWorkflowTemplates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyWorkflowTemplate(self, request, context):
        """@alias=/ModifyWorkflowTemplate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeAvailableWorkflowTemplateComponents(self, request, context):
        """@alias=/DescribeAvailableWorkflowTemplateComponents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowTemplateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWorkflowTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkflowTemplates,
                    request_deserializer=workflow__template__pb2.CreateWorkflowTemplatesRequest.FromString,
                    response_serializer=workflow__template__pb2.CreateWorkflowTemplatesResponse.SerializeToString,
            ),
            'DescribeWorkflowTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeWorkflowTemplates,
                    request_deserializer=workflow__template__pb2.DescribeWorkflowTemplatesRequest.FromString,
                    response_serializer=workflow__template__pb2.DescribeWorkflowTemplatesResponse.SerializeToString,
            ),
            'DescribeWorkflowTemplateDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeWorkflowTemplateDetails,
                    request_deserializer=workflow__template__pb2.DescribeWorkflowTemplateDetailsRequest.FromString,
                    response_serializer=workflow__template__pb2.DescribeWorkflowTemplateDetailsResponse.SerializeToString,
            ),
            'DeleteWorkflowTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWorkflowTemplates,
                    request_deserializer=workflow__template__pb2.DeleteWorkflowTemplatesRequest.FromString,
                    response_serializer=workflow__template__pb2.DeleteWorkflowTemplatesResponse.SerializeToString,
            ),
            'ModifyWorkflowTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyWorkflowTemplate,
                    request_deserializer=workflow__template__pb2.ModifyWorkflowTemplateRequest.FromString,
                    response_serializer=workflow__template__pb2.ModifyWorkflowTemplateResponse.SerializeToString,
            ),
            'DescribeAvailableWorkflowTemplateComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeAvailableWorkflowTemplateComponents,
                    request_deserializer=workflow__template__pb2.DescribeAvailableWorkflowTemplateComponentsRequest.FromString,
                    response_serializer=workflow__template__pb2.DescribeAvailableWorkflowTemplateComponentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trpc.media.workflowtemplate.WorkflowTemplate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WorkflowTemplate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWorkflowTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trpc.media.workflowtemplate.WorkflowTemplate/CreateWorkflowTemplates',
            workflow__template__pb2.CreateWorkflowTemplatesRequest.SerializeToString,
            workflow__template__pb2.CreateWorkflowTemplatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeWorkflowTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trpc.media.workflowtemplate.WorkflowTemplate/DescribeWorkflowTemplates',
            workflow__template__pb2.DescribeWorkflowTemplatesRequest.SerializeToString,
            workflow__template__pb2.DescribeWorkflowTemplatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeWorkflowTemplateDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trpc.media.workflowtemplate.WorkflowTemplate/DescribeWorkflowTemplateDetails',
            workflow__template__pb2.DescribeWorkflowTemplateDetailsRequest.SerializeToString,
            workflow__template__pb2.DescribeWorkflowTemplateDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteWorkflowTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trpc.media.workflowtemplate.WorkflowTemplate/DeleteWorkflowTemplates',
            workflow__template__pb2.DeleteWorkflowTemplatesRequest.SerializeToString,
            workflow__template__pb2.DeleteWorkflowTemplatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyWorkflowTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trpc.media.workflowtemplate.WorkflowTemplate/ModifyWorkflowTemplate',
            workflow__template__pb2.ModifyWorkflowTemplateRequest.SerializeToString,
            workflow__template__pb2.ModifyWorkflowTemplateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DescribeAvailableWorkflowTemplateComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/trpc.media.workflowtemplate.WorkflowTemplate/DescribeAvailableWorkflowTemplateComponents',
            workflow__template__pb2.DescribeAvailableWorkflowTemplateComponentsRequest.SerializeToString,
            workflow__template__pb2.DescribeAvailableWorkflowTemplateComponentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
