# -*- coding: utf-8 -*-
"""This is RPC module
Code generated by trpc-go/trpc-go-cmdline. DO NOT EDIT.
Source: person_retrieval.proto
"""
from typing import List, Callable, Tuple

from trpc import client
from trpc import codec
from trpc import server
from trpc import context
from trpc.codec.message import Message
from . import pb

#pylint: disable=unnecessary-pass


# PersonRetrievalService defines service
class PersonRetrievalServicer:
    """Abstract base class of server"""
    
    #pylint: disable=invalid-name
    async def CreatePersonRetrievalTask(self, ctx: context.Context, request: pb.CreatePersonRetrievalTaskRequest) -> pb.CreatePersonRetrievalTaskResponse:
        """Abstract rpc method of server
        :param ctx: context of data processing.
        :param request: object of pb.
        """
        raise NotImplementedError('Method not implemented!')
    #pylint: disable=invalid-name
    async def DescribePersonRetrievalTaskData(self, ctx: context.Context, request: pb.DescribePersonRetrievalTaskDataRequest) -> pb.DescribePersonRetrievalTaskDataResponse:
        """Abstract rpc method of server
        :param ctx: context of data processing.
        :param request: object of pb.
        """
        raise NotImplementedError('Method not implemented!')
    #pylint: disable=invalid-name
    async def RetrievalImage(self, ctx: context.Context, request: pb.RetrievalImageRequest) -> pb.RetrievalImageResponse:
        """Abstract rpc method of server
        :param ctx: context of data processing.
        :param request: object of pb.
        """
        raise NotImplementedError('Method not implemented!')

PersonRetrievalServiceName = "trpc.media.personretrieval.PersonRetrieval"  # pylint: disable=invalid-name

# add PersonRetrievalServicer to server
# pylint: disable=invalid-name
def register_PersonRetrievalServicer_server(svr: server.Server, servicer: PersonRetrievalServicer, fix_rpc_name: bool = False):
    """Register service to server"""
    rpc_method_handlers = []
    rpc_stream_handlers = []
    
    rpc_method_handlers.append(
        server.Method(
            name="/CreatePersonRetrievalTask",
            req_cls=pb.CreatePersonRetrievalTaskRequest,
            rsp_cls=pb.CreatePersonRetrievalTaskResponse,
            impl_func=servicer.CreatePersonRetrievalTask))
    
    rpc_method_handlers.append(
        server.Method(
            name="/DescribePersonRetrievalTaskData",
            req_cls=pb.DescribePersonRetrievalTaskDataRequest,
            rsp_cls=pb.DescribePersonRetrievalTaskDataResponse,
            impl_func=servicer.DescribePersonRetrievalTaskData))
    
    rpc_method_handlers.append(
        server.Method(
            name="/RetrievalImage",
            req_cls=pb.RetrievalImageRequest,
            rsp_cls=pb.RetrievalImageResponse,
            impl_func=servicer.RetrievalImage))
    
    desc = server.ServiceDesc(
        service_name="/" + PersonRetrievalServiceName,
        methods=rpc_method_handlers)

    svr.register(desc, fix_rpc_name)


# client proxy
class PersonRetrievalClientProxy:
    """Client proxy"""
    
    def CreatePersonRetrievalTask(self, ctx: context.Context, request: pb.CreatePersonRetrievalTaskRequest, options: List[Callable] = None) -> pb.CreatePersonRetrievalTaskResponse:
        """Client stream method
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of rsp pb
        """
        pass

    async def asyncCreatePersonRetrievalTask(self, ctx: context.Context, request: pb.CreatePersonRetrievalTaskRequest, options: List[Callable] = None) -> pb.CreatePersonRetrievalTaskResponse:
        """Async client stream method
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of rsp pb
        """
        pass
    
    def DescribePersonRetrievalTaskData(self, ctx: context.Context, request: pb.DescribePersonRetrievalTaskDataRequest, options: List[Callable] = None) -> pb.DescribePersonRetrievalTaskDataResponse:
        """Client stream method
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of rsp pb
        """
        pass

    async def asyncDescribePersonRetrievalTaskData(self, ctx: context.Context, request: pb.DescribePersonRetrievalTaskDataRequest, options: List[Callable] = None) -> pb.DescribePersonRetrievalTaskDataResponse:
        """Async client stream method
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of rsp pb
        """
        pass
    
    def RetrievalImage(self, ctx: context.Context, request: pb.RetrievalImageRequest, options: List[Callable] = None) -> pb.RetrievalImageResponse:
        """Client stream method
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of rsp pb
        """
        pass

    async def asyncRetrievalImage(self, ctx: context.Context, request: pb.RetrievalImageRequest, options: List[Callable] = None) -> pb.RetrievalImageResponse:
        """Async client stream method
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of rsp pb
        """
        pass
    

class PersonRetrievalClientProxyImpl(PersonRetrievalClientProxy):
    """Client proxy implementation"""
    def __init__(self, service_name: str = None, fix_rpc_name: bool = True):
        self.client = client.get_client()
        self.options = {}

    @staticmethod
    def _clone_client_message(ctx: context.Context, rpc_name: str, callee_method: str) -> Tuple[context.Context, Message]:
        """Clone client message
        :param ctx: context of data processing.
        :param rpc_name: name of rpc.
        :param callee_method: method of callee
        :return: tuple
        """
        ctx, msg = codec.clone_client_message(ctx)
        msg.set_client_rpc_name(rpc_name)
        msg.set_callee_service_name(PersonRetrievalServiceName)
        msg.set_callee_method(callee_method)
        return ctx, msg

    
    def CreatePersonRetrievalTask(self, ctx: context.Context, request: pb.CreatePersonRetrievalTaskRequest, options: List[Callable] = None) -> pb.CreatePersonRetrievalTaskResponse:
        """Client rpc method implementation
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of pb
        """
        rsp_cls = pb.CreatePersonRetrievalTaskResponse
        options = options or []

        ctx, msg = self._clone_client_message(ctx, '/CreatePersonRetrievalTask', 'CreatePersonRetrievalTask')
        return self.client.invoke_sync(ctx, request, rsp_cls, options)

    async def asyncCreatePersonRetrievalTask(self, ctx: context.Context, request: pb.CreatePersonRetrievalTaskRequest, options: List[Callable] = None) -> pb.CreatePersonRetrievalTaskResponse:
        """Async client rpc method implementation
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of pb
        """
        rsp_cls = pb.CreatePersonRetrievalTaskResponse
        options = options or []

        ctx, msg = self._clone_client_message(ctx, '/CreatePersonRetrievalTask', 'CreatePersonRetrievalTask')
        rsp = await self.client.invoke(ctx, request, rsp_cls, options)
        return rsp
    
    def DescribePersonRetrievalTaskData(self, ctx: context.Context, request: pb.DescribePersonRetrievalTaskDataRequest, options: List[Callable] = None) -> pb.DescribePersonRetrievalTaskDataResponse:
        """Client rpc method implementation
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of pb
        """
        rsp_cls = pb.DescribePersonRetrievalTaskDataResponse
        options = options or []

        ctx, msg = self._clone_client_message(ctx, '/DescribePersonRetrievalTaskData', 'DescribePersonRetrievalTaskData')
        return self.client.invoke_sync(ctx, request, rsp_cls, options)

    async def asyncDescribePersonRetrievalTaskData(self, ctx: context.Context, request: pb.DescribePersonRetrievalTaskDataRequest, options: List[Callable] = None) -> pb.DescribePersonRetrievalTaskDataResponse:
        """Async client rpc method implementation
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of pb
        """
        rsp_cls = pb.DescribePersonRetrievalTaskDataResponse
        options = options or []

        ctx, msg = self._clone_client_message(ctx, '/DescribePersonRetrievalTaskData', 'DescribePersonRetrievalTaskData')
        rsp = await self.client.invoke(ctx, request, rsp_cls, options)
        return rsp
    
    def RetrievalImage(self, ctx: context.Context, request: pb.RetrievalImageRequest, options: List[Callable] = None) -> pb.RetrievalImageResponse:
        """Client rpc method implementation
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of pb
        """
        rsp_cls = pb.RetrievalImageResponse
        options = options or []

        ctx, msg = self._clone_client_message(ctx, '/RetrievalImage', 'RetrievalImage')
        return self.client.invoke_sync(ctx, request, rsp_cls, options)

    async def asyncRetrievalImage(self, ctx: context.Context, request: pb.RetrievalImageRequest, options: List[Callable] = None) -> pb.RetrievalImageResponse:
        """Async client rpc method implementation
        :param ctx: context of data processing.
        :param request: object of pb.
        :param options: list of setting functions
        :return: object of pb
        """
        rsp_cls = pb.RetrievalImageResponse
        options = options or []

        ctx, msg = self._clone_client_message(ctx, '/RetrievalImage', 'RetrievalImage')
        rsp = await self.client.invoke(ctx, request, rsp_cls, options)
        return rsp
    