# -*- coding: utf-8 -*-
"""This is pb module
Code generated by trpc-go/trpc-go-cmdline. DO NOT EDIT.
Source: person_user_define.proto
"""

# pylint: disable=wildcard-import
# pylint: disable=unused-wildcard-import
from .common_pb2 import *
from google.protobuf.any_pb2 import *
from google.protobuf.struct_pb2 import *
from .person_user_define_pb2 import *

