# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toolkit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='toolkit.proto',
  package='trpc.media.toolkit',
  syntax='proto3',
  serialized_options=b'ZUgithub.com/Tencent-media-asset-system-sdk/media-platform-sdk-go/protobuf-spec/toolkit',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtoolkit.proto\x12\x12trpc.media.toolkit\x1a\x0c\x63ommon.proto\"\xbb\x01\n\x08ToolInfo\x12\x0e\n\x06ToolID\x18\x01 \x01(\t\x12\x10\n\x08ToolName\x18\x02 \x01(\t\x12\x17\n\x0fToolDescription\x18\x03 \x01(\t\x12\x13\n\x0bToolIconURI\x18\x04 \x01(\t\x12\x14\n\x0cToolEntryURI\x18\x05 \x01(\t\x12\x36\n\nToolAccess\x18\x08 \x01(\x0e\x32\".trpc.media.toolkit.ToolAccessType\x12\x11\n\tToolOrder\x18\t \x01(\x05\"\x19\n\x17\x44\x65scribeToolkitsRequest\"I\n\x18\x44\x65scribeToolkitsResponse\x12-\n\x07ToolSet\x18\x01 \x03(\x0b\x32\x1c.trpc.media.toolkit.ToolInfo\"\x17\n\x15ToolkitDefaultRequest\"\x18\n\x16ToolkitDefaultResponse*_\n\x10ToolProviderType\x12\x19\n\x15TOOL_PROVIDER_UNKNOWN\x10\x00\x12\x19\n\x15TOOL_PROVIDER_AIMEDIA\x10\x01\x12\x15\n\x11TOOL_PROVIDER_PCG\x10\x02*u\n\x10ToolCategoryType\x12\x19\n\x15TOOL_CATEGORY_UNKNOWN\x10\x00\x12\x1f\n\x1bTOOL_CATEGORY_VIDEO_QUALITY\x10\x01\x12%\n!TOOL_CATEGORY_VIDEO_UNDERSTANDING\x10\x02*]\n\x0eToolAccessType\x12\x17\n\x13TOOL_ACCESS_UNKNOWN\x10\x00\x12\x18\n\x14TOOL_ACCESS_INTERNAL\x10\x01\x12\x18\n\x14TOOL_ACCESS_EXTERNAL\x10\x02\x32x\n\x07Toolkit\x12m\n\x10\x44\x65scribeToolkits\x12+.trpc.media.toolkit.DescribeToolkitsRequest\x1a,.trpc.media.toolkit.DescribeToolkitsResponseBWZUgithub.com/Tencent-media-asset-system-sdk/media-platform-sdk-go/protobuf-spec/toolkitb\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_TOOLPROVIDERTYPE = _descriptor.EnumDescriptor(
  name='ToolProviderType',
  full_name='trpc.media.toolkit.ToolProviderType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOOL_PROVIDER_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOOL_PROVIDER_AIMEDIA', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOOL_PROVIDER_PCG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=394,
  serialized_end=489,
)
_sym_db.RegisterEnumDescriptor(_TOOLPROVIDERTYPE)

ToolProviderType = enum_type_wrapper.EnumTypeWrapper(_TOOLPROVIDERTYPE)
_TOOLCATEGORYTYPE = _descriptor.EnumDescriptor(
  name='ToolCategoryType',
  full_name='trpc.media.toolkit.ToolCategoryType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOOL_CATEGORY_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOOL_CATEGORY_VIDEO_QUALITY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOOL_CATEGORY_VIDEO_UNDERSTANDING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=491,
  serialized_end=608,
)
_sym_db.RegisterEnumDescriptor(_TOOLCATEGORYTYPE)

ToolCategoryType = enum_type_wrapper.EnumTypeWrapper(_TOOLCATEGORYTYPE)
_TOOLACCESSTYPE = _descriptor.EnumDescriptor(
  name='ToolAccessType',
  full_name='trpc.media.toolkit.ToolAccessType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOOL_ACCESS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOOL_ACCESS_INTERNAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOOL_ACCESS_EXTERNAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=610,
  serialized_end=703,
)
_sym_db.RegisterEnumDescriptor(_TOOLACCESSTYPE)

ToolAccessType = enum_type_wrapper.EnumTypeWrapper(_TOOLACCESSTYPE)
TOOL_PROVIDER_UNKNOWN = 0
TOOL_PROVIDER_AIMEDIA = 1
TOOL_PROVIDER_PCG = 2
TOOL_CATEGORY_UNKNOWN = 0
TOOL_CATEGORY_VIDEO_QUALITY = 1
TOOL_CATEGORY_VIDEO_UNDERSTANDING = 2
TOOL_ACCESS_UNKNOWN = 0
TOOL_ACCESS_INTERNAL = 1
TOOL_ACCESS_EXTERNAL = 2



_TOOLINFO = _descriptor.Descriptor(
  name='ToolInfo',
  full_name='trpc.media.toolkit.ToolInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ToolID', full_name='trpc.media.toolkit.ToolInfo.ToolID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ToolName', full_name='trpc.media.toolkit.ToolInfo.ToolName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ToolDescription', full_name='trpc.media.toolkit.ToolInfo.ToolDescription', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ToolIconURI', full_name='trpc.media.toolkit.ToolInfo.ToolIconURI', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ToolEntryURI', full_name='trpc.media.toolkit.ToolInfo.ToolEntryURI', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ToolAccess', full_name='trpc.media.toolkit.ToolInfo.ToolAccess', index=5,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ToolOrder', full_name='trpc.media.toolkit.ToolInfo.ToolOrder', index=6,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=239,
)


_DESCRIBETOOLKITSREQUEST = _descriptor.Descriptor(
  name='DescribeToolkitsRequest',
  full_name='trpc.media.toolkit.DescribeToolkitsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=266,
)


_DESCRIBETOOLKITSRESPONSE = _descriptor.Descriptor(
  name='DescribeToolkitsResponse',
  full_name='trpc.media.toolkit.DescribeToolkitsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ToolSet', full_name='trpc.media.toolkit.DescribeToolkitsResponse.ToolSet', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=341,
)


_TOOLKITDEFAULTREQUEST = _descriptor.Descriptor(
  name='ToolkitDefaultRequest',
  full_name='trpc.media.toolkit.ToolkitDefaultRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=366,
)


_TOOLKITDEFAULTRESPONSE = _descriptor.Descriptor(
  name='ToolkitDefaultResponse',
  full_name='trpc.media.toolkit.ToolkitDefaultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=392,
)

_TOOLINFO.fields_by_name['ToolAccess'].enum_type = _TOOLACCESSTYPE
_DESCRIBETOOLKITSRESPONSE.fields_by_name['ToolSet'].message_type = _TOOLINFO
DESCRIPTOR.message_types_by_name['ToolInfo'] = _TOOLINFO
DESCRIPTOR.message_types_by_name['DescribeToolkitsRequest'] = _DESCRIBETOOLKITSREQUEST
DESCRIPTOR.message_types_by_name['DescribeToolkitsResponse'] = _DESCRIBETOOLKITSRESPONSE
DESCRIPTOR.message_types_by_name['ToolkitDefaultRequest'] = _TOOLKITDEFAULTREQUEST
DESCRIPTOR.message_types_by_name['ToolkitDefaultResponse'] = _TOOLKITDEFAULTRESPONSE
DESCRIPTOR.enum_types_by_name['ToolProviderType'] = _TOOLPROVIDERTYPE
DESCRIPTOR.enum_types_by_name['ToolCategoryType'] = _TOOLCATEGORYTYPE
DESCRIPTOR.enum_types_by_name['ToolAccessType'] = _TOOLACCESSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ToolInfo = _reflection.GeneratedProtocolMessageType('ToolInfo', (_message.Message,), {
  'DESCRIPTOR' : _TOOLINFO,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.ToolInfo)
  })
_sym_db.RegisterMessage(ToolInfo)

DescribeToolkitsRequest = _reflection.GeneratedProtocolMessageType('DescribeToolkitsRequest', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBETOOLKITSREQUEST,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.DescribeToolkitsRequest)
  })
_sym_db.RegisterMessage(DescribeToolkitsRequest)

DescribeToolkitsResponse = _reflection.GeneratedProtocolMessageType('DescribeToolkitsResponse', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBETOOLKITSRESPONSE,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.DescribeToolkitsResponse)
  })
_sym_db.RegisterMessage(DescribeToolkitsResponse)

ToolkitDefaultRequest = _reflection.GeneratedProtocolMessageType('ToolkitDefaultRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOOLKITDEFAULTREQUEST,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.ToolkitDefaultRequest)
  })
_sym_db.RegisterMessage(ToolkitDefaultRequest)

ToolkitDefaultResponse = _reflection.GeneratedProtocolMessageType('ToolkitDefaultResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOOLKITDEFAULTRESPONSE,
  '__module__' : 'toolkit_pb2'
  # @@protoc_insertion_point(class_scope:trpc.media.toolkit.ToolkitDefaultResponse)
  })
_sym_db.RegisterMessage(ToolkitDefaultResponse)


DESCRIPTOR._options = None

_TOOLKIT = _descriptor.ServiceDescriptor(
  name='Toolkit',
  full_name='trpc.media.toolkit.Toolkit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=705,
  serialized_end=825,
  methods=[
  _descriptor.MethodDescriptor(
    name='DescribeToolkits',
    full_name='trpc.media.toolkit.Toolkit.DescribeToolkits',
    index=0,
    containing_service=None,
    input_type=_DESCRIBETOOLKITSREQUEST,
    output_type=_DESCRIBETOOLKITSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOOLKIT)

DESCRIPTOR.services_by_name['Toolkit'] = _TOOLKIT

# @@protoc_insertion_point(module_scope)
